<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SocialNetworkAnalysis.Algorithms\SocialNetworkAnalysis.Algorithms.csproj" />
    <ProjectReference Include="..\SocialNetworkAnalysis.Core\SocialNetworkAnalysis.Core.csproj" />
    <ProjectReference Include="..\SocialNetworkAnalysis.Services\SocialNetworkAnalysis.Services.csproj" />
  </ItemGroup>

</Project>
